### ISSUE TITLE
Format Python code using Black

### ISSUE THREAD

**Issue by za** [williballenthin/INDXParse#55]
Hi there, 

Do you mind formatting the Python source code using [Black](https://github.com/psf/black)? I know it's opinionated, but IMHO having a standardized format will make the code _easier to read_.

I can prepare the PR and we may check the diff.

**Comment by williballenthin** [comment]
hi @za 

in #38 we mention a goal of using Black to format the code, along with isort and a few other linters. so, yes, this is on the roadmap. 

however, i don't want to do a one-time formatting; instead, we'll want to configure CI to check the formatting on each push and release etc. i think we'll use the pre-commit tool and github actions for this. 

@ajnelson-nist and @sldouglas-nist have been working on many code quality updates recently, so i'd like to give them a chance to do this, if they'd like (no pressure). otherwise, we can coordinate here about how to apply Black to this project.

**Comment by williballenthin** [comment]
i'll leave this issue open as the central point of discussion for configuring Black to run during CI and beyond, ideally with pre-commit.

**Comment by ajnelson-nist** [comment]
PR #57 has been opened to address this Issue.

**Comment by williballenthin** [comment]
closed in #57
